import { writeFileSync } from "node:fs";
import { loadSwagger } from "../src/swagger.js";
import { isReadSafe, isCollectionDelete } from "../src/accessPolicy.js";
import { MULTIPART_FILE_FIELD } from "../src/request.js";

// Review categories describe potential effects from the bundled contract. They
// are not runtime authorization and do not assert live validation of each API.
const categories: Record<string, string> = {};
for (const [category, tags] of [
  ["Access/security", ["Account", "Authentication", "OAuth", "MultiFactorAuthentication", "Openid", "Password", "UserGroup"]],
  ["Infrastructure", ["Ainvr", "CloudStorage", "Configuration", "Engine Model", "Gateway", "License", "Module", "Nvr", "Plugin", "Utility"]],
  ["Analytics/processing", ["AnalyticConfig", "Camera", "EngineProfile", "ExternalCamera", "Footage", "Job", "LineSet", "Roi", "Tracking"]],
  ["Alerts/delivery", ["Alert", "AlertRule", "AlertTrigger", "AuditTrail", "Event", "False-report"]],
  ["Recognition records", ["Face", "FaceCategory", "FaceMatch", "FaceTarget", "IdentityRecognition", "LicensePlate", "LicensePlateCategory", "LicensePlateTarget"]],
  ["Organization/metadata", ["CameraGroup", "Filter", "Hashtag", "IndoorMap", "Scene"]],
  ["Processing/query review", ["Detection", "Image", "Media", "Onvif", "Resource", "SceneObject", "Sound"]],
] as const) for (const tag of tags) categories[tag] = category;

const queryReview = new Set([
  "POST /api/alerts/pairs", "POST /api/ainvrs/validate", "POST /api/cloud-storages/buckets/list",
  "POST /api/cloud-storages/regions", "POST /api/face/search", "POST /api/face/similarity",
  "POST /api/face/statistics", "POST /api/face/keys", "POST /api/media/stream",
  "POST /api/nvrs/connection", "POST /api/onvif/rtsps", "POST /api/openid-providers/connection",
  "POST /api/resources/estimation", "POST /api/scenes/image", "POST /api/scene-objects/search",
  "POST /api/scene-objects/search/image",
]);
const control = "POST /api/cameras/{cameraId}/jobs";
const maintenance = new Set(["PATCH /api/cameras/{cameraId}", "PATCH /api/alertRules/{alertRuleId}"]);
const ctx = loadSwagger();
const rows = ctx.tags.flatMap(group => group.operations).filter(op => op.method !== "GET" && !isReadSafe(op));
const escape = (s: string) => s.replaceAll("|", "\\|").replaceAll("\n", " ");
const lines = ["# Write-operation review inventory", "",
  "Generated by `node --import tsx scripts/generate-write-inventory.ts` from the bundled API and review categories.",
  "See [CUSTOMER-WRITE-POLICY.md](CUSTOMER-WRITE-POLICY.md) for decisions, evidence and profile limits.", "",
  `This inventory covers **${rows.length} non-GET operations outside the verified read-safe POST list**.`,
  "Inclusion does not prove an operation mutates data. Query-shaped POSTs remain unverified for read-only admission.",
  "Categories describe potential impact from the contract, not live observations or numerical risk scores.", "",
  "Every operation is off by default in native HTTP configuration. Only the named profiles opt into writes.",
  "Collection deletes are rejected by remote policy. File uploads are unavailable remotely; an optional-file operation may also have other inputs, which remain deferred here.",
  "All other review/defer decisions are recommendations, not new server-enforced restrictions.", "",
  "| Operation | Documented purpose | Impact area | Customer decision |",
  "| --- | --- | --- | --- |",
];
for (const op of rows) {
  if (!categories[op.tag]) throw new Error(`Unreviewed tag: ${op.tag}`);
  const upload = op.parameters.some(p => p.in === "formData" && p.type === "file") || !!MULTIPART_FILE_FIELD[op.id];
  let decision = "Off; workflow review required";
  if (isCollectionDelete(op)) decision = "Blocked by remote collection-delete policy";
  else if (upload) decision = "Off; upload workflow deferred";
  else if (op.id === control) decision = "Camera-control and maintenance profiles; start/stop evidence";
  else if (maintenance.has(op.id)) decision = "Maintenance profile only; limited-field test evidence";
  else if (queryReview.has(op.id)) decision = "Off; query/connection semantics need validation";
  else if (op.method === "DELETE") decision = "Off; removal/cancellation review required";
  else if (["Access/security", "Infrastructure"].includes(categories[op.tag])) decision = "Off; administrator workflow";
  else if (op.id === "PUT /api/jobs") decision = "Off; all-jobs scope";
  else if (["POST /api/alertTriggers", "POST /api/false-report"].includes(op.id)) decision = "Off; authorized external delivery required";
  lines.push(`| \`${op.id}\` | ${escape(op.summary ?? "Not specified")} | ${categories[op.tag]} | ${decision} |`);
}
writeFileSync(new URL("../docs/WRITE-OPERATIONS.md", import.meta.url), lines.join("\n") + "\n");
console.log(`Reviewed inventory: ${rows.length} operations; ${rows.filter(isCollectionDelete).length} blocked collection deletes.`);
